### ISSUE TITLE
Session slides are linked to the template

### ISSUE THREAD

**Issue by marchanlon** [microsoft/aitour-get-started-with-fabric#25]
The session slides link in SESSION_RESOURCES.md links to a template for the slides and not the slide content itself.

**Comment by Jcardif** [comment]
I’ve double-checked this, and both PowerPoint presentations link to the correct decks. The presentation in the  _Session Delivery Resources PowerPoint_ includes a template slide on **slide 3**, which is the only slide that requires updates.

This slide _(shown below)_ needs to be updated with the names and headshots of the speakers and proctors.

![Image](https://github.com/user-attachments/assets/09d6f982-11d7-4bcf-95a2-3945e8d78859)
